// 生成独立 profile 插件文件(从构建产物 lib/),并更新 profile 的 patch 行。
// 这是"改完源码 → 让本地 profile 生效"的唯一入口,避免手工同步 host 代码漂移。
//
// 用法:
//   node scripts/build-profile.mjs             # 默认写入 ~/.dsh/profiles/web/plugins/ 并更新 patch 行
//   node scripts/build-profile.mjs <outdir>    # 写入指定目录(测试用,不更新 patch 行)
//
// 生成的文件是 require 包装器:每次加载先清除 lib/ 的 require.cache,保证
// 改完源码重新 build 后,热加载拿到的是最新代码。
import { readFileSync, writeFileSync, readdirSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = fileURLToPath(new URL('..', import.meta.url))
const libDir = join(repoRoot, 'lib')
const home = process.env.HOME ?? ''
const defaultOut = join(home, '.dsh', 'profiles', 'web', 'plugins')
const outDir = process.argv[2] || defaultOut
const isDefaultOut = outDir === defaultOut

// 校验 lib 已构建
try {
  readFileSync(join(libDir, 'index.js'))
} catch {
  console.error('请先运行构建: npm run build (tsc -p tsconfig.json)')
  process.exit(1)
}

// 计算下一个版本号(基于现有 ds-balance-vN.js)
const existing = readdirSync(outDir)
  .filter((f) => /^ds-balance-v\d+\.js$/.test(f))
  .map((f) => parseInt(f.match(/^ds-balance-v(\d+)\.js$/)[1], 10))
const next = (existing.length > 0 ? Math.max(...existing) : 9) + 1
const name = `ds-balance-v${next}.js`

const wrapper = [
  '// GENERATED by scripts/build-profile.mjs — do not edit.',
  `// 独立 profile 插件:require 构建产物 ${libDir},清除缓存保证最新。`,
  `const __libDir = ${JSON.stringify(libDir)}`,
  'for (const __k of Object.keys(require.cache)) {',
  '  if (__k.indexOf(__libDir) === 0) delete require.cache[__k]',
  '}',
  "module.exports = require(__libDir + '/index.js')",
].join('\n') + '\n'

// 写入新包装文件,清理旧版本
writeFileSync(join(outDir, name), wrapper)
for (const f of readdirSync(outDir)) {
  if (/^ds-balance-v\d+\.js$/.test(f) && f !== name) rmSync(join(outDir, f))
}

// 更新 patch 行(仅默认输出目录)
if (isDefaultOut) {
  const patchPath = join(home, '.dsh', 'profiles', 'web', 'cordis.patch.yml')
  const patch = readFileSync(patchPath, 'utf8')
  const updated = patch.replace(/name: '\.\/plugins\/ds-balance-v\d+\.js'/, `name: './plugins/${name}'`)
  if (updated === patch) {
    console.error('警告:patch 行未匹配到 ds-balance-vN.js(可能已被手动改名)')
  }
  writeFileSync(patchPath, updated)
  console.log(`已生成 ${join(outDir, name)}`)
  console.log(`patch 行 → ./plugins/${name}`)
} else {
  console.log(`已生成 ${join(outDir, name)}(测试输出,未更新 patch)`)
}
