// 从纯 JS 内联文件生成 TS 模板字符串(card-script.ts / cost-script.ts)。
// 这是"编辑注入脚本"的唯一正确入口:脚本内容在 src/scripts/*.inline.js(普通 JS,
// 直接 node --check 可验),转义由本生成器程序化完成——模板字面量中的反斜杠、
// 反引号、${ 全部由构造保证正确,杜绝手写转义的层层叠加。
//
// 用法: node scripts/build-scripts.mjs   (已接入 npm run build)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const inlineDir = join(root, 'src', 'scripts')
const srcDir = join(root, 'src')

/** 模板字面量转义:反斜杠双写、反引号与 ${ 前加反斜杠(防止求值层插值/截断) */
function escapeTemplate(s) {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

function generate(name, inlineFile, outFile, header) {
  const content = readFileSync(join(inlineDir, inlineFile), 'utf8')
  // 注入时带 <script> 包装(与历史行为一致)
  const wrapped = `<script>\n${content}\n</script>`
  const out = header + 'export const ' + name + ' = `' + escapeTemplate(wrapped) + '`\n'
  writeFileSync(join(srcDir, outFile), out)
}

// 卡片脚本由三个片段拼接:card.inline.js(外壳 + STYLE + drag)+ card-fmt.inline.js(纯函数)+ card-render.inline.js(渲染)。
// 用 indexOf + slice 拼接(禁用 String.replace:片段内容含 $ 会被展开)。
const CARD_SLOTS = [
  { slot: '// CARD_FMT_SLOT', file: 'card-fmt.inline.js' },
  { slot: '// CARD_RENDER_SLOT', file: 'card-render.inline.js' },
]
function spliceSlot(main, slot, replacement) {
  const idx = main.indexOf(slot)
  if (idx === -1) throw new Error('card.inline.js 缺少 ' + slot + ' 占位')
  return main.slice(0, idx) + replacement.trimEnd() + '\n' + main.slice(idx + slot.length)
}
function generateCard(outFile, header) {
  let content = readFileSync(join(inlineDir, 'card.inline.js'), 'utf8')
  for (const { slot, file } of CARD_SLOTS) {
    const frag = readFileSync(join(inlineDir, file), 'utf8')
    content = spliceSlot(content, slot, frag)
  }
  const wrapped = `<script>\n${content}\n</script>`
  const out = header + 'export const CARD_SCRIPT = `' + escapeTemplate(wrapped) + '`\n'
  writeFileSync(join(srcDir, outFile), out)
}

const cardHeader = [
  '// 注入的卡片脚本(GENERATED by scripts/build-scripts.mjs — 编辑 src/scripts/card.inline.js)。',
  '// 注意:',
  '// 1) 内容不能出现反引号或 ${(生成器已转义,内联源里也不要写);',
  '// 2) 内联源是普通 JS,`\\n` 就是换行转义,无需考虑模板层;',
  '// 3) 注入用切片拼接(见 src/index.ts injectScript),禁用 String.replace。',
  '',
].join('\n')

const costHeader = [
  '// 注入的费用脚本(GENERATED by scripts/build-scripts.mjs — 编辑 src/scripts/cost.inline.js)。注意点同 card-script.ts。',
  '',
].join('\n')

generateCard('card-script.ts', cardHeader)
generate('COST_SCRIPT', 'cost.inline.js', 'cost-script.ts', costHeader)
console.log('✅ scripts 已从 inline.js 生成(card-script.ts / cost-script.ts)')
