// 注入的卡片脚本(GENERATED by scripts/build-scripts.mjs — 编辑 src/scripts/card.inline.js)。
// 注意:
// 1) 内容不能出现反引号或 ${(生成器已转义,内联源里也不要写);
// 2) 内联源是普通 JS,`\n` 就是换行转义,无需考虑模板层;
// 3) 注入用切片拼接(见 src/index.ts injectScript),禁用 String.replace。
export const CARD_SCRIPT = `<script>
(function () {
  if (window.__dsBalanceInstalled) return;
  window.__dsBalanceInstalled = true;
  var POLL_MS = 10000;
  var TICK_MS = 30000;
  var last = null;
  var STYLE = '.ds-balance-card{position:fixed;top:60px;right:14px;z-index:9999;width:256px;box-sizing:border-box;max-height:240px;overflow:hidden;padding:9px 14px 10px;border-radius:12px;background:rgba(28,30,36,.88);color:#e8eaf0;font:12px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;box-shadow:0 4px 16px rgba(0,0,0,.28);cursor:pointer;user-select:none;backdrop-filter:blur(6px);-webkit-backdrop-filter:blur(6px);}' +
    '.ds-balance-card:hover{background:rgba(38,41,48,.92);}.ds-balance-card__head{display:flex;align-items:center;gap:6px;opacity:.75;margin-bottom:2px;white-space:nowrap;}.ds-balance-card__dot{width:7px;height:7px;border-radius:50%;background:#4D6BFE;flex:none;}.ds-balance-card__dot--err{background:#f87171;}' +
    '@keyframes dsCardPulse{0%,100%{opacity:1;box-shadow:0 0 0 0 rgba(77,107,254,.45);}50%{opacity:.5;box-shadow:0 0 8px 4px rgba(77,107,254,.22);}}.ds-balance-card__dot--active{animation:dsCardPulse 1.5s ease-in-out infinite;}.ds-balance-card--dragging{cursor:grabbing!important;opacity:.85;user-select:none;}' +
    '.ds-balance-card__rate{font-size:11px;font-weight:600;opacity:.9;white-space:nowrap;margin-left:auto;display:none;}.ds-balance-card__rate--on{display:inline;}.ds-balance-card__tpsnum{font-weight:650;}.ds-balance-card__tpsnum--on{color:#4ade80;}.ds-balance-card__models{font-size:10px;opacity:.7;margin-top:4px;text-align:left;letter-spacing:.2px;}.ds-balance-card__forecast{font-size:11px;opacity:.5;margin-top:4px;text-align:left;letter-spacing:.3px;}.ds-balance-card__forecast--on{opacity:.75;}.ds-balance-card__cost{font-weight:650;color:#fff;}' +
    '.ds-balance-card__time{font-size:9px;font-weight:400;opacity:.4;letter-spacing:.3px;line-height:1;}.ds-balance-card__amt{font-size:17px;font-weight:650;letter-spacing:.2px;}.ds-balance-card__amtlabel{font-size:10.5px;font-weight:400;opacity:.6;letter-spacing:.3px;}.ds-balance-card__src{font-size:10px;opacity:.75;padding:0 5px;border:1px solid rgba(128,128,128,.35);border-radius:999px;white-space:nowrap;}.ds-balance-card__switch{font-size:9px;opacity:.6;cursor:pointer;padding:0 2px;}.ds-balance-card__modelsel{display:inline-flex;align-items:center;gap:2px;cursor:pointer;}' +
    '.ds-balance-card__divider{border-top:1px solid rgba(128,128,128,.22);margin-top:6px;}' +
    '.ds-balance-card__brand{background:linear-gradient(90deg,#4D6BFE 0%,#4D6BFE 40%,#C9D6FF 50%,#4D6BFE 60%,#4D6BFE 100%);color:#0000;-webkit-text-fill-color:transparent;background-position:100% 0;background-size:250% 100%;-webkit-background-clip:text;background-clip:text;}.ds-balance-card__brand--active{animation:dsBrandShimmer 1.8s linear infinite;}@keyframes dsBrandShimmer{to{background-position:0 0}}@media (prefers-reduced-motion:reduce){.ds-balance-card__brand--active{background-position:0 0;background-size:100% 100%;animation:none}}' +
    '.ds-balance-card__period{margin-top:4px;padding-top:4px;border-top:1px solid rgba(128,128,128,.25);display:flex;align-items:center;justify-content:flex-start;gap:6px;flex-wrap:wrap;white-space:nowrap;}.ds-balance-card__badge{font-size:10.5px;font-weight:650;padding:1px 7px;border-radius:999px;letter-spacing:.3px;}.ds-balance-card__badge--peak{background:rgba(251,146,60,.2);color:#fbbf24;border:1px solid rgba(251,146,60,.45);}.ds-balance-card__badge--offpeak{background:rgba(52,211,153,.16);color:#34d399;border:1px solid rgba(52,211,153,.4);}' +
    '.ds-balance-card__next{opacity:.8;font-size:11px;}.ds-balance-card__amtrow{display:flex;align-items:flex-end;gap:10px;flex-wrap:wrap;}.ds-balance-card__amtcol{display:flex;flex-direction:column;align-items:flex-start;gap:2px;min-width:0;}.ds-balance-card__usage{font-size:10.5px;font-weight:400;opacity:.72;letter-spacing:.2px;margin-left:auto;}.ds-balance-card__err{color:#fca5a5;font-size:11px;max-width:230px;}' +
    '.ds-balance-card__menu{position:fixed;z-index:10000;min-width:180px;max-width:260px;box-sizing:border-box;background:rgba(28,30,36,.96);color:#e8eaf0;border:1px solid rgba(128,128,128,.3);border-radius:8px;box-shadow:0 6px 20px rgba(0,0,0,.35);padding:4px;font:12px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);}' +
    '.ds-balance-card__menuitem{font-size:11px;padding:5px 8px;border-radius:6px;cursor:pointer;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}' +
    '.ds-balance-card__menuitem:hover{background:rgba(77,107,254,.22);}' +
    '.ds-balance-card__menuitem--current{color:#4D6BFE;font-weight:600;}' +
    '.ds-balance-card__menuitem--current::before{content:"✓ ";}' +
    'body:not([data-ds-dark-theme]) .ds-balance-card{background:rgba(255,255,255,.95);color:#23262f;box-shadow:0 4px 16px rgba(0,0,0,.12);border:1px solid rgba(0,0,0,.07);}body:not([data-ds-dark-theme]) .ds-balance-card:hover{background:#fff;}body:not([data-ds-dark-theme]) .ds-balance-card__period{border-top-color:rgba(0,0,0,.12);}body:not([data-ds-dark-theme]) .ds-balance-card__divider{border-top-color:rgba(0,0,0,.12);}body:not([data-ds-dark-theme]) .ds-balance-card__badge--peak{background:rgba(251,146,60,.14);color:#b45309;border-color:rgba(180,83,9,.4);}body:not([data-ds-dark-theme]) .ds-balance-card__badge--offpeak{background:rgba(16,185,129,.12);color:#047857;border-color:rgba(4,120,87,.35);}body:not([data-ds-dark-theme]) .ds-balance-card__err{color:#b91c1c;}body:not([data-ds-dark-theme]) .ds-balance-card__cost{color:#000;}' +
    'body:not([data-ds-dark-theme]) .ds-balance-card__menu{background:rgba(255,255,255,.98);color:#23262f;border-color:rgba(0,0,0,.12);}body:not([data-ds-dark-theme]) .ds-balance-card__menuitem:hover{background:rgba(77,107,254,.12);}';
  var styleEl = document.createElement('style');
  styleEl.textContent = STYLE;
  document.head.appendChild(styleEl);

  var root = document.createElement('div');
  root.className = 'ds-balance-card';
  root.title = '点击立即刷新';
  var drag = { mode: false, timer: null, sx: 0, sy: 0, ox: 0, oy: 0, suppress: false };
  function dragDown(e) {
    var rect = root.getBoundingClientRect();
    drag.sx = e.clientX; drag.sy = e.clientY;
    drag.ox = rect.left; drag.oy = rect.top;
    drag.timer = setTimeout(function () {
      drag.mode = true;
      root.classList.add('ds-balance-card--dragging');
    }, 350);
  }
  function dragMove(e) {
    if (!drag.mode) {
      if (drag.timer && (Math.abs(e.clientX - drag.sx) > 6 || Math.abs(e.clientY - drag.sy) > 6)) {
        clearTimeout(drag.timer); drag.timer = null;
      }
      return;
    }
    root.style.right = 'auto';
    root.style.left = (drag.ox + (e.clientX - drag.sx)) + 'px';
    root.style.top = (drag.oy + (e.clientY - drag.sy)) + 'px';
  }
  function dragUp() {
    clearTimeout(drag.timer); drag.timer = null;
    if (drag.mode) {
      drag.mode = false;
      drag.suppress = true;
      root.classList.remove('ds-balance-card--dragging');
      try {
        localStorage.setItem('dsh-balance-card-pos', JSON.stringify({ left: root.style.left, top: root.style.top }));
      } catch (e) {}
    }
  }
  root.addEventListener('pointerdown', dragDown);
  window.addEventListener('pointermove', dragMove);
  window.addEventListener('pointerup', dragUp);
  root.addEventListener('click', function () {
    if (drag.suppress) { drag.suppress = false; return; }
    poll();
  });
  try {
    var savedPos = localStorage.getItem('dsh-balance-card-pos');
    if (savedPos) {
      var pos = JSON.parse(savedPos);
      if (pos && (pos.left || pos.top)) {
        root.style.left = pos.left; root.style.top = pos.top; root.style.right = 'auto';
      }
    }
  } catch (e) {}
  document.body.appendChild(root);

    function makeEl(tag, cls, text) {
    var node = document.createElement(tag);
    if (cls) node.className = cls;
    if (text !== undefined) node.textContent = text;
    return node;
  }

  function fmt(b) {
    var sym = b.currency === 'CNY' ? '¥' : b.currency === 'USD' ? '$' : b.currency + ' ';
    var n = Number(b.total);
    return { sym: sym, text: isFinite(n) ? n.toFixed(2) : String(b.total) };
  }

  function countdownText(ms) {
    var total = Math.max(0, Math.floor((ms - Date.now()) / 60000));
    var h = Math.floor(total / 60), m = total % 60;
    if (h <= 0 && m <= 0) return '即将调整';
    return h > 0 ? h + '小时' + m + '分' : m + '分';
  }

  function fmtNextAt(ts, now) {
    var d = new Date(ts);
    var n = now === undefined ? new Date() : new Date(now);
    var dayStart = new Date(n.getFullYear(), n.getMonth(), n.getDate()).getTime();
    var nextStart = new Date(d.getFullYear(), d.getMonth(), d.getDate()).getTime();
    var diff = Math.round((nextStart - dayStart) / 86400000);
    var label = diff === 0 ? '今日' : diff === 1 ? '明日' : (d.getMonth() + 1) + '月' + d.getDate() + '日';
    var h = d.getHours();
    var ampm = h >= 12 ? 'PM' : 'AM';
    var h12 = h % 12 || 12;
    var mm = String(d.getMinutes()).padStart(2, '0');
    return '(' + label + h12 + ':' + mm + ampm + ')';
  }

  function localWindows(windowsUtc) {
    // 把 UTC 波峰窗口换算成本地时间显示(如 "10:00-13:00, 15:00-19:00")
    var offsetMin = new Date().getTimezoneOffset(); // 本地→UTC 需加的分(UTC+9 为 -540)
    var parts = [];
    (windowsUtc || []).forEach(function (w) {
      var a = ((w[0] - offsetMin / 60) % 24 + 24) % 24;
      var b = ((w[1] - offsetMin / 60) % 24 + 24) % 24;
      var z = function (h) { return String(Math.floor(h)).padStart(2, '0') + ':' + String(Math.round((h % 1) * 60)).padStart(2, '0'); };
      parts.push(z(a) + '-' + z(b));
    });
    return parts.join(', ');
  }

  function pickCurrencies(infos) {
    // 只显示有余额的币种;两个都有余额时 USD 优先;都无余额时保留全部(显示 0)
    var withBalance = (infos || []).filter(function (b) { return Number(b.total) > 0; });
    if (withBalance.length === 0) return infos || [];
    withBalance.sort(function (a, b) {
      if (a.currency === 'USD') return -1;
      if (b.currency === 'USD') return 1;
      return 0;
    });
    return withBalance;
  }

  function usageText(usd, currency) {
    // 近24h 只显示一种货币:跟随主余额币种(USD 原样,其余按汇率换算人民币)
    if (currency === 'USD') return '$' + usd.toFixed(2);
    return '¥' + (usd * 7.1).toFixed(2);
  }

  function sourceLabel(provider) {
    // 模型来源:官方 API 显示中文,其它(网关/OpenRouter/本机路由)显示路由名
    if (provider === 'deepseek-official') return '官方 API';
    return provider;
  }

  function pulseDuration(tps) {
    // 呼吸灯脉动频率按 tok/s 分级:越快越短
    if (tps >= 300) return 0.6;
    if (tps >= 100) return 1.0;
    if (tps >= 20) return 1.6;
    return 2.4;
  }

  function currentSessionId() {
    try {
      var raw = localStorage.getItem('dsh.sessions.current');
      if (!raw) return null;
      var o = JSON.parse(raw);
      return (o && o.sessionId) || null;
    } catch (e) { return null; }
  }

  function tpsValue(activity) {
    // 有消耗显示实时 tps;空闲(或过期)清 0,不保留过期值
    if (!activity || !activity.active) return 0;
    return activity.tps;
  }

  function agoText(ts, now) {
    var s = Math.max(0, Math.round((now - ts) / 1000));
    if (s < 10) return '刚刚';
    if (s < 60) return s + 's前';
    var m = Math.round(s / 60);
    if (m < 60) return m + 'm前';
    var h = Math.round(m / 60);
    if (h < 24) return h + 'h前';
    return Math.round(h / 24) + 'd前';
  }

  function fmtTokens(n) {
    if (n >= 1000000) return (n / 1000000).toFixed(1) + 'M';
    if (n >= 1000) return (n / 1000).toFixed(1) + 'k';
    return String(n);
  }

  function fmtCost(cny) {
    if (!isFinite(cny) || cny <= 0) return '¥0';
    if (cny >= 1) return '¥' + cny.toFixed(2);
    if (cny >= 0.01) return '¥' + cny.toFixed(3);
    return '¥' + cny.toFixed(4);
  }

  function fmtM(n) {
    var m = Math.max(n, 100000) / 1000000;
    return m >= 1 ? Math.round(m) + 'M' : m.toFixed(1) + 'M';
  }

  function modelKeyFromLabel(label) {
    if (!label) return null;
    var t = String(label).toLowerCase().replace(/[^a-z0-9]/g, '');
    var keys = ['deepseek-v4-flash', 'deepseek-v4-pro', 'deepseek-reasoner', 'deepseek-chat'];
    for (var i = 0; i < keys.length; i++) if (t.indexOf(keys[i].replace(/-/g, '')) !== -1) return keys[i];
    return null;
  }
  function currentModelFromDom() {
    try { var el = document.querySelector('.gTaGEG_trigger'); return el ? modelKeyFromLabel(el.textContent) : null; }
    catch (e) { return null; }
  }

  function fmtTps(n) { return String(Math.round(Number(n) || 0)); }

  function shortModel(m) {
    if (!m) return '?';
    if (m === 'deepseek-v4-flash') return 'deepseek';
    if (m === 'deepseek-v4-pro') return 'pro';
    if (m.indexOf('qwen') !== -1) return 'qwen3-vl';
    var seg = m.split('/');
    return seg[seg.length - 1];
  }

  function originClass(sel) {
    // 按"来源类型"归类:deepseek 官方 vs qwen(视觉),其余按模型名尾段
    if (sel.provider === 'deepseek-official') return 'deepseek';
    if (sel.model && sel.model.indexOf('qwen') !== -1) return 'qwen';
    return sel.model ? sel.model.split('/').pop() : '?';
  }

  function originLabel(cls) {
    if (cls === 'deepseek') return 'DeepSeek 官方';
    if (cls === 'qwen') return 'Qwen 阿里云';
    return cls;
  }

  function modelOptions(groups, current) {
    // 只保留 deepseek 官方 / qwen 两类(每类一项),过滤掉 polyglot 等其它来源。
    // 当前模型命中某类时,该类的代表模型用 current,避免切换时意外降级(如 v4-pro → v4-flash)。
    var out = [];
    var seen = {};
    var curCls = current ? originClass(current) : null;
    (groups || []).forEach(function (g) {
      (g.models || []).forEach(function (m) {
        var cls = originClass({ provider: g.id, model: m.id });
        if (cls !== 'deepseek' && cls !== 'qwen') return;
        if (seen[cls]) return;
        seen[cls] = true;
        if (curCls === cls) {
          out.push({ provider: current.provider, model: current.model, cls: cls });
        } else {
          out.push({ provider: g.id, model: m.id, cls: cls });
        }
      });
    });
    return out;
  }

    function renderSkeleton() {
    root.textContent = '';
    var head = makeEl('div', 'ds-balance-card__head');
    head.appendChild(makeEl('span', 'ds-balance-card__dot'));
    head.appendChild(makeEl('span', null, 'DeepSeek'));
    root.appendChild(head);
    var amtRow = makeEl('div', 'ds-balance-card__amtrow');
    var amtCol = makeEl('div', 'ds-balance-card__amtcol');
    amtCol.appendChild(makeEl('span', 'ds-balance-card__time', ''));
    amtCol.appendChild(makeEl('span', 'ds-balance-card__amtlabel', '余额'));
    amtRow.appendChild(amtCol);
    amtRow.appendChild(makeEl('span', 'ds-balance-card__amt', '…'));
    root.appendChild(amtRow);
  }

  function render(data) {
    root.textContent = '';
    if (!data || data.ok !== true) {
      var reason = data && data.reason === 'no-key' ? '未配置 API key' : '查询失败';
      root.appendChild(makeEl('div', 'ds-balance-card__err', reason));
      return;
    }
    var dot = makeEl('span', 'ds-balance-card__dot');
    var dotTitle = '';
    if (!data.isAvailable) {
      dot.className += ' ds-balance-card__dot--err';
      dotTitle = '账户不可用';
    } else if (data.activity && data.activity.active) {
      dot.className += ' ds-balance-card__dot--active';
      dot.style.animationDuration = pulseDuration(data.activity.tps) + 's';
      dotTitle = '运行中 ' + fmtTps(data.activity.tps) + ' tok/s';
    } else {
      dotTitle = '空闲';
    }
    dot.title = dotTitle;
    var head = makeEl('div', 'ds-balance-card__head');
    head.appendChild(dot);
    var brand = makeEl('span', 'ds-balance-card__brand');
    brand.textContent = 'DeepSeek';
    if (data.activity && data.activity.active) {
      brand.classList.add('ds-balance-card__brand--active');
      brand.style.animationDuration = pulseDuration(data.activity.tps) + 's';
    }
    head.appendChild(brand);
    var selWrap = makeEl('span', 'ds-balance-card__modelsel');
    if (data.source && data.source.provider) {
      var src = makeEl('span', 'ds-balance-card__src', sourceLabel(data.source.provider));
      src.title = '模型: ' + (data.source.model || '?');
      selWrap.appendChild(src);
    }
    var sw = makeEl('span', 'ds-balance-card__switch', '▼');
    sw.title = '选择模型';
    selWrap.appendChild(sw);
    selWrap.onclick = function (e) {
      if (e) e.stopPropagation();
      openModelMenu(sw);
    };
    head.appendChild(selWrap);
    if (data.activity) {
      var tpsOn = data.activity.active;
      var tpsNum = makeEl('span', 'ds-balance-card__tpsnum' + (tpsOn ? ' ds-balance-card__tpsnum--on' : ''), fmtTps(tpsValue(data.activity)));
      var rateRow = makeEl('span', 'ds-balance-card__rate' + (tpsOn ? ' ds-balance-card__rate--on' : ''));
      rateRow.appendChild(tpsNum);
      rateRow.appendChild(makeEl('span', null, ' tok/s'));
      rateRow.title = tpsOn ? '运行中 · 实时 ' + fmtTps(data.activity.tps) + ' tok/s' : '空闲 · 速率 0';
      head.appendChild(rateRow);
    }
    var list = pickCurrencies(data.infos);
    var mainCur = list[0] ? list[0].currency : 'CNY';
    var main = fmt(list[0] || { currency: 'CNY', total: '--' });
    var amtRow = makeEl('div', 'ds-balance-card__amtrow');
    var amtCol = makeEl('div', 'ds-balance-card__amtcol');
    var asOf = typeof data.asOf === 'number' ? data.asOf : Date.now();
    var timeEl = makeEl('span', 'ds-balance-card__time', agoText(asOf, Date.now()));
    timeEl.title = '更新于 ' + new Date(asOf).toLocaleTimeString('zh-CN', { hour12: false });
    amtCol.appendChild(timeEl);
    amtCol.appendChild(makeEl('span', 'ds-balance-card__amtlabel', '余额'));
    amtRow.appendChild(amtCol);
    var amtSpan = makeEl('span', 'ds-balance-card__amt', main.sym + main.text);
    var mainInfo = list[0];
    if (mainInfo) {
      var gAmt = fmt({ currency: mainInfo.currency, total: mainInfo.granted });
      var tAmt = fmt({ currency: mainInfo.currency, total: mainInfo.toppedUp });
      amtSpan.title = '充值 ' + tAmt.sym + tAmt.text + ' / 赠送 ' + gAmt.sym + gAmt.text;
    }
    amtRow.appendChild(amtSpan);
    if (data.usage24h) {
      var u = data.usage24h;
      var usage = makeEl('span', 'ds-balance-card__usage', '近24h ' + (mainCur === 'USD' ? usageText(u.usd, 'USD') : (typeof u.cny === 'number' ? '¥' + u.cny.toFixed(2) : usageText(u.usd, 'CNY'))));
          var uparts = [];
    if (u.flatUsd > 0) uparts.push('平峰 $' + u.flatUsd.toFixed(3));
    if (u.peakUsd > 0) uparts.push('波峰 $' + u.peakUsd.toFixed(3));
    if (u.offUsd > 0) uparts.push('低峰 $' + u.offUsd.toFixed(3));
    usage.title = '仅本机 Harness 会话;官方政策价估算' + (uparts.length ? '(' + uparts.join(' / ') + ')' : '') + ' / 调用 ' + u.calls + ' 次\\n更新时间 ' + new Date(u.asOf).toLocaleTimeString('zh-CN', { hour12: false });
      amtRow.appendChild(usage);
    }
    root.appendChild(head);
    root.appendChild(amtRow);
    if (data.period) {
      var peak = data.period.mode === 'peak';
      var badge = makeEl('span', 'ds-balance-card__badge ' + (peak ? 'ds-balance-card__badge--peak' : 'ds-balance-card__badge--offpeak'), peak ? '波峰' : '低峰');
      var period = makeEl('div', 'ds-balance-card__period');
      period.title = '波峰时段(本地): ' + localWindows(data.period.windowsUtc);
      period.appendChild(badge);
      period.appendChild(makeEl('span', 'ds-balance-card__next', '下次调整 ' + countdownText(data.period.nextAt) + fmtNextAt(data.period.nextAt)));
      root.appendChild(period);
    }
    root.appendChild(makeEl('div', 'ds-balance-card__divider'));
    if (data.byModel && data.byModel.length > 1) {
      var pm = makeEl('div', 'ds-balance-card__models');
      pm.textContent = data.byModel.map(function (b) {
        return shortModel(b.model) + ' ' + fmtM(b.input + b.cacheRead + b.output) + ' · ' + fmtCost(b.costCny);
      }).join('  ');
      pm.title = data.byModel.map(function (b) {
        return b.model + ': ' + fmtTokens(b.input + b.cacheRead + b.output) + ' tok · ¥' + b.costCny.toFixed(4) + '(' + b.calls + ' 次)';
      }).join('\\n');
      root.appendChild(pm);
    }
    var fc = makeEl('div', 'ds-balance-card__forecast');
    var p = data.prediction;
    if (p && p.totalTokens > 0) {
      fc.classList.add('ds-balance-card__forecast--on');
      fc.textContent = '🔮 此次预测 ' + fmtM(p.totalTokens) + ' tok · ';
      fc.appendChild(makeEl('span', 'ds-balance-card__cost', fmtCost(p.costCny)));
      fc.title = '预计输入 ' + fmtTokens(p.predictedInput) + '(含上下文 ' + fmtTokens(p.contextTokens) + ')+ 输出 ' + fmtTokens(p.predictedOutput) + ' · ' + (p.model || '未知模型') + ' 估算\\n数据为本地日志估算,仅供参考';
    } else {
      fc.textContent = '🔮';
      fc.title = '预测模块开发中(规划中)';
    }
    root.appendChild(fc);
  }


  function openModelMenu(anchor) {
    var wasOpen = !!document.querySelector('.ds-balance-card__menu');
    closeModelMenu();
    if (wasOpen) return;
    var sid = currentSessionId();
    if (!sid) return;
    fetch('/api/session.models', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type: 'client-request', rpcId: String(Date.now()), method: 'session.models', payload: { sessionId: sid } }) })
      .then(function (r) { return r.json(); })
      .then(function (d) { return d && d.result && d.result.value; })
      .then(function (v) {
        var opts = modelOptions(v && v.groups, v && v.current);
        if (!opts.length) return;
        var menu = makeEl('div', 'ds-balance-card__menu');
        opts.forEach(function (o) {
          var item = makeEl('div', 'ds-balance-card__menuitem', originLabel(o.cls));
          item.title = o.provider + '/' + o.model;
          if (v.current && originClass(v.current) === o.cls) item.classList.add('ds-balance-card__menuitem--current');
          item.onclick = function (e) {
            if (e) e.stopPropagation();
            selectModel(o.provider, o.model);
            closeModelMenu();
          };
          menu.appendChild(item);
        });
        document.body.appendChild(menu);
        var rect = anchor.getBoundingClientRect();
        menu.style.top = (rect.bottom + 4) + 'px';
        menu.style.right = (window.innerWidth - rect.right) + 'px';
        document.addEventListener('pointerdown', onMenuDocDown, true);
      })
      .catch(function () {});
  }

  function onMenuDocDown(e) {
    var menu = document.querySelector('.ds-balance-card__menu');
    if (!menu) { document.removeEventListener('pointerdown', onMenuDocDown, true); return; }
    if (menu.contains(e.target)) return;
    var sel = document.querySelector('.ds-balance-card__modelsel');
    if (sel && sel.contains(e.target)) return;
    var sw = document.querySelector('.ds-balance-card__switch');
    if (sw && sw.contains(e.target)) return;
    closeModelMenu();
  }

  function closeModelMenu() {
    var m = document.querySelector('.ds-balance-card__menu');
    if (m && m.parentNode) m.parentNode.removeChild(m);
    document.removeEventListener('pointerdown', onMenuDocDown, true);
  }

  function selectModel(provider, model) {
    var sid = currentSessionId();
    if (!sid) return;
    fetch('/api/session.selectModel', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type: 'client-request', rpcId: String(Date.now()), method: 'session.selectModel', payload: { sessionId: sid, provider: provider, model: model } }) })
      .then(function (r) { return r.json(); })
      .then(function (d) { if (d && d.result && d.result.ok === true) setTimeout(poll, 150); })
      .catch(function () {});
  }

  function saveCache(data) {
    try { localStorage.setItem('dsh-balance-card-data', JSON.stringify(data)); } catch (e) {}
  }
  function loadCache() {
    try {
      var raw = localStorage.getItem('dsh-balance-card-data');
      if (!raw) return null;
      return JSON.parse(raw);
    } catch (e) { return null; }
  }

  var polling = false;
  function poll() {
    if (polling) return;
    polling = true;
    var sid = currentSessionId();
    var qs = '';
    if (sid) qs += '?session=' + encodeURIComponent(sid);
    var model = currentModelFromDom();
    if (model) qs += (qs ? '&' : '?') + 'model=' + encodeURIComponent(model);
    fetch('/ds-balance' + qs, { cache: 'no-store' })
      .then(function (r) { return r.json(); })
      .then(function (d) { last = d; saveCache(d); render(d); })
      .catch(function () { polling = false; render({ ok: false, reason: 'http' }); });
    polling = false;
  }

  var POLL_ACTIVITY_MS = 1500;
  var activityPolling = false;
  function pollActivity() {
    if (activityPolling) return;
    activityPolling = true;
    var sid = currentSessionId();
    fetch('/ds-activity' + (sid ? '?session=' + encodeURIComponent(sid) : ''), { cache: 'no-store' })
      .then(function (r) { return r.json(); })
      .then(function (d) { activityPolling = false; if (d && d.activity) applyActivity(d.activity); })
      .catch(function () { activityPolling = false; });
  }
  function applyActivity(a) {
    var dot = root.querySelector('.ds-balance-card__dot');
    if (!dot || !a) return;
    var on = !!a.active;
    dot.classList.remove('ds-balance-card__dot--active', 'ds-balance-card__dot--err');
    if (on) {
      dot.classList.add('ds-balance-card__dot--active');
      dot.style.animationDuration = pulseDuration(a.tps) + 's';
      dot.title = '运行中 ' + fmtTps(a.tps) + ' tok/s';
    } else {
      dot.title = '空闲';
    }
    var brand = root.querySelector('.ds-balance-card__brand');
    if (brand) {
      brand.classList.toggle('ds-balance-card__brand--active', on);
      if (on) brand.style.animationDuration = pulseDuration(a.tps) + 's';
    }
    var rate = root.querySelector('.ds-balance-card__rate');
    if (rate) {
      var num = rate.querySelector('.ds-balance-card__tpsnum');
      if (num) {
        num.textContent = fmtTps(tpsValue(a));
        num.classList.toggle('ds-balance-card__tpsnum--on', on);
      }
      rate.classList.toggle('ds-balance-card__rate--on', on);
      rate.title = on ? '运行中 · 实时 ' + fmtTps(a.tps) + ' tok/s' : '空闲 · 速率 0';
    }
  }

  var cached = loadCache();
  if (cached) { last = cached; render(cached); } else { renderSkeleton(); }
  poll();
  setInterval(poll, POLL_MS);
  setInterval(function () { if (last) render(last); }, TICK_MS);
  pollActivity();
  setInterval(pollActivity, POLL_ACTIVITY_MS);
})();

</script>`
